name: Build NovaSMP

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Zip Utility
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Run Build Script
        run: python build.py

      - name: Compile JAR with Maven
        working-directory: NovaSMP-Plugin
        run: mvn clean package -B

      - name: Upload Finished Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NovaSMP-Completed-Files
          path: |
            NovaSMP-Plugin/target/*.jar
            NovaSMP-ResourcePack.zip
